# Generated by Django 2.2.6 on 2019-10-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
