# Generated by Django 2.2.6 on 2019-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20191010_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bank',
            field=models.CharField(default='', max_length=20),
        ),
    ]
